version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  rotate_study_population:
    run: python:latest python analysis/rotate_study_population.py
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input-last.feather

  generate_summary_notebook:
    run: python:latest jupyter nbconvert notebooks/summary.ipynb --to=html --output-dir=output/ --execute
    needs: [generate_study_population, rotate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/summary.html
