version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition --index-date-range "2021-01-01 to today by month"
    outputs:
      highly_sensitive:
        cohort: output/generate_study_population/input_*.feather

  concat_study_population:
    run: python:latest python analysis/concat_study_population.py
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  rotate_study_population:
    run: python:latest python analysis/rotate_study_population.py
    needs: [concat_study_population]
    outputs:
      highly_sensitive:
        cohort: output/input-last.feather

  generate_summary_notebook:
    run: python:latest jupyter nbconvert notebooks/summary.ipynb --to=html --output-dir=output/ --execute --ExecutePreprocessor.timeout=86400
    needs: [concat_study_population, rotate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/summary.html
